### ISSUE TITLE
Email Verification

### ISSUE THREAD

**Issue by yocohen77** [olgakent/BookHunter#7]
How to send an e-mail verification link to a new user

**Comment by yocohen77** [comment]
http://www.scotchmedia.com/tutorials/express/authentication/3/02
https://appdividend.com/2017/08/11/send-email-in-node-js/

**Comment by yocohen77** [comment]
Create a verification email template

**Comment by olgakent** [comment]
When a user signs up, instead of logging them in immediately we are going to email them a confirmation token to ensure they provided a real email. For this, we can use  a couple of packages, crypto and nodemailer, to assist in token creation and emailing.

**Comment by MatthewVardi** [comment]
We will use the restricted form submission to restrict non-hunter users from registering on BookHuner for now.

In the future, if time permits, we will look into email verification / confirmation.
